### ISSUE TITLE
is sampler change not affected?

### ISSUE THREAD

**Issue by tigrazone** [TomClabault/HIPRT-Path-Tracer#10]
I change GGXAnisotropicSampleFunction in src\HostDeviceCommon\KernelOptions.h but image saved same.
what wrong? caching or what?

**Comment by TomClabault** [comment]
Hi @tigrazone !

Did you notice a recompilation of the shaders after changing the option?

Also, the only supported options currently are `GGX_VNDF_SAMPLING` and `GGX_VNDF_SPHERICAL_CAPS`. Both of these options should give the exact same results. The only difference should be that `GGX_VNDF_SPHERICAL_CAPS` is slightly faster.

But the rendered image should be the same in both cases.

**Comment by tigrazone** [comment]
I implement [GGX_VNDF_BOUNDED](https://github.com/tigrazone/HIPRT-Path-Tracer/blob/30623042d4b35dbeededeb1adb03dad67c6c0746/src/Device/includes/Sampling.h#L322).
I change KernelOptions.h and restart program. Program recompile shaders.
I kill cache after changes and try to off Direct Lighting for tests.
Also I select Global Performance Preset High Quality, Render stopping condition Max Samples Count 256.
I recheck and see GGX_VNDF_SAMPLING and GGX_VNDF_SPHERICAL_CAPS different

GGX_VNDF_SAMPLING
![GGX_VNDF_SAMPLING 11 03 2024 15 55 25 - 256sp @ 1279x699 - 53 7954s](https://github.com/user-attachments/assets/e8b46978-654a-46ea-8866-110b37671671)

GGX_VNDF_SPHERICAL_CAPS
![GGX_VNDF_SPHERICAL_CAPS 11 03 2024 15 59 02 - 256sp @ 1279x699 - 52 9556s](https://github.com/user-attachments/assets/2c3395f5-5a4e-4fc3-a2c9-74ba0f2e7a03)

**Comment by tigrazone** [comment]
GGX_VNDF_BOUNDED look like GGX_VNDF_SPHERICAL_CAPS and I dont know why
![GGX_VNDF_BOUNDED 11 03 2024 16 33 47 - 256sp @ 1279x699 - 53 3182s](https://github.com/user-attachments/assets/79adcd21-fe8e-4095-adc1-472c77c3ad4e)

**Comment by tigrazone** [comment]
I implement GGX_VNDF_BOUNDED in other my renderer and image was little bit different.
Take a look [1](https://x.com/tigratigratigra/status/1838146271606952353) and [2](https://x.com/tigratigratigra/status/1838136244028555362) and [3](https://x.com/tigratigratigra/status/1838135942416146470)

**Comment by TomClabault** [comment]
> I implement [GGX_VNDF_BOUNDED](https://github.com/tigrazone/HIPRT-Path-Tracer/blob/30623042d4b35dbeededeb1adb03dad67c6c0746/src/Device/includes/Sampling.h#L322).

Awesome! That's a super nice contribution!

> I recheck and see GGX_VNDF_SAMPLING and GGX_VNDF_SPHERICAL_CAPS different

That was a little bit misleading on my part. With these two sampling strategies, we shouldn't see a noticeable difference in convergence since `GGX_VNDF_SPHERICAL_CAPS` is only a faster version of `GGX_VNDF_SAMPLING`. But the noise may be a little bit different indeed.

> GGX_VNDF_BOUNDED look like GGX_VNDF_SPHERICAL_CAPS and I dont know why

I looked at your implementation and saw nothing weird. This should work. Maybe you can try to return a `float3(0, 0, 0)` from `GGX_VNDF_bounded_sample()` to make sure that the function is called.

Also, I pushed some UI additions on the `main` branch in the "Debug" panel of ImGui to manipulate the shader cache so maybe this can make you task easier.

![Capture](https://github.com/user-attachments/assets/3edde2f8-3ba1-4d2f-9d11-5162127b1ad4)

Also after you pull, you will have to run `git submodule update --init` because I made some changes to a submodule.

**Comment by tigrazone** [comment]
My implementation based on pdf. It contains code of sample change. I speedup it a little

**Comment by tigrazone** [comment]
difference is exists. I rerender with off ReSTIR and compare with photoshop
![GGX_VNDF_BOUNDED-vs-GGX_VNDF_SPHERICAL_CAPS](https://github.com/user-attachments/assets/e1b8cb43-179f-4b4e-ab5e-27ddca04a03f)

code from pdf
![pdf1](https://github.com/user-attachments/assets/bc0e09fa-9d8e-4b40-b3bb-4916df975542)

**Comment by TomClabault** [comment]
How many samples was that rendered with? The difference seems very minimal and I think bounded VNDF sampling should benefit more than that on rough surfaces.

**Comment by tigrazone** [comment]
all screenshots 256 spp.
last compare screenshot from 128 spp GGX_VNDF_BOUNDED, GGX_VNDF_SPHERICAL_CAPS

**Comment by TomClabault** [comment]
Actually now that I think about it, the materials in this scene are dielectrics, not metals. This means that they do not use the GGX distribution and so that's why bounded VNDF sampling doesn't really improve variance here.

Would you be willing to open a pull request so that I can test and merge your contribution?

**Comment by tigrazone** [comment]
Ok
